version: '3.8'

services:
  lama-model:
    image: montijnb/lama-model:latest
    ports:
      - "8000:8000"
    volumes:
      - ./surroundings_data:/app/surroundings_data
      - ./output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - TORCH_HOME=/app/.torch
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  yolo-model:
    image: montijnb/yolo-model:latest
    volumes:
      - ./surroundings_data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]