version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./surroundings_data:/app/surroundings_data
      - ./output:/app/output
      - ./model/YOLO/weights:/app/model/YOLO/weights
      - ./model/lama:/app/model/lama
    environment:
      - TORCH_HOME=/app/.torch
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G